### ISSUE TITLE
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

### ISSUE THREAD

**Issue by ampledata** [ampledata/pymma#1]
```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/srv/pymultimonaprs/local/lib/python2.7/site-packages/pymultimonaprs/gate.py", line 134, in _socket_worker
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

**Comment by ampledata** [comment]
Possibly related to `socket.error` being lost in the thread context.
